/**
 * Easyscholar-style multi-dimensional journal rankings.
 *
 * Data sources:
 * - CCF: China Computer Federation Recommended List (2022)
 * - CSSCI: Chinese Social Sciences Citation Index (南大核心)
 * - PKU Core: 北大中文核心期刊目录 (2023 edition)
 * - JCR: Journal Citation Reports quartiles (2024)
 * - ABDC: Australian Business Deans Council Journal Quality List (2022)
 * - FMS: Financial Times / Management Science recommended (50 journals)
 * - 中科院分区: Chinese Academy of Sciences zones 3 & 4
 */

// ─── CCF 中国计算机学会推荐期刊/会议 ─────────────
// Covers CS, IS, AI journals relevant to management/IS research
export const CCF_RANKINGS: Record<string, "A" | "B" | "C"> = {
  // === CCF-A Journals ===
  "journal of the acm": "A",
  "ieee transactions on information theory": "A",
  "information and computation": "A",
  "siam journal on computing": "A",
  "ieee transactions on pattern analysis and machine intelligence": "A",
  "international journal of computer vision": "A",
  "journal of machine learning research": "A",
  "artificial intelligence": "A",
  "ieee transactions on knowledge and data engineering": "A",
  "ieee transactions on visualization and computer graphics": "A",
  "ieee transactions on software engineering": "A",
  "acm transactions on computer systems": "A",
  "acm transactions on database systems": "A",
  "acm transactions on graphics": "A",
  "acm transactions on information systems": "A",
  "acm transactions on software engineering and methodology": "A",
  "ieee transactions on mobile computing": "A",
  "ieee transactions on parallel and distributed systems": "A",
  "journal of cryptology": "A",
  "ieee transactions on image processing": "A",
  "acm computing surveys": "A",
  "proceedings of the ieee": "A",

  // === CCF-A Conferences ===
  "aaai": "A",
  "neurips": "A",
  "nips": "A",
  "cvpr": "A",
  "iccv": "A",
  "icml": "A",
  "ijcai": "A",
  "sigmod": "A",
  "vldb": "A",
  "sigkdd": "A",
  "kdd": "A",
  "www": "A",
  "sigir": "A",
  "acl": "A",
  "icse": "A",
  "fse": "A",
  "osdi": "A",
  "sosp": "A",
  "sigcomm": "A",
  "mobicom": "A",
  "infocom": "A",
  "chi": "A",
  "ccs": "A",
  "crypto": "A",
  "eurocrypt": "A",
  "stoc": "A",
  "focs": "A",
  "sc": "A",
  "hpca": "A",
  "micro": "A",
  "isca": "A",

  // === CCF-B Journals ===
  "journal of artificial intelligence research": "B",
  "machine learning": "B",
  "neural computation": "B",
  "neural networks": "B",
  "pattern recognition": "B",
  "knowledge and information systems": "B",
  "ieee transactions on neural networks and learning systems": "B",
  "ieee transactions on cybernetics": "B",
  "ieee transactions on fuzzy systems": "B",
  "ieee transactions on evolutionary computation": "B",
  "information sciences": "B",
  "expert systems with applications": "B",
  "decision support systems": "B",
  "information processing and management": "B",
  "information and management": "B",
  "journal of management information systems": "B",
  "journal of strategic information systems": "B",
  "european journal of information systems": "B",
  "journal of the association for information systems": "B",
  "acm transactions on internet technology": "B",
  "ieee transactions on services computing": "B",
  "data mining and knowledge discovery": "B",
  "acm transactions on intelligent systems and technology": "B",
  "ieee intelligent systems": "B",
  "computer supported cooperative work": "B",
  "journal of computer-mediated communication": "B",
  "ieee transactions on big data": "B",
  "ieee transactions on computational social systems": "B",

  // === CCF-B Conferences ===
  "emnlp": "B",
  "naacl": "B",
  "coling": "B",
  "eccv": "B",
  "wsdm": "B",
  "cikm": "B",
  "icdm": "B",
  "icde": "B",
  "ecai": "B",
  "aamas": "B",
  "uai": "B",
  "icws": "B",
  "icsoc": "B",

  // === CCF-C Journals ===
  "applied intelligence": "C",
  "computational intelligence": "C",
  "engineering applications of artificial intelligence": "C",
  "intelligent data analysis": "C",
  "journal of intelligent information systems": "C",
  "natural language engineering": "C",
  "computers and operations research": "C",
  "electronic commerce research and applications": "C",
  "internet research": "C",
  "journal of computer information systems": "C",
  "behaviour and information technology": "C",
  "international journal of human-computer studies": "C",
  "interacting with computers": "C",
  "journal of organizational computing and electronic commerce": "C",
  "telematics and informatics": "C",
};

// ─── CSSCI 南大核心（管理学/经济学/社会科学相关期刊）─────
// Chinese Social Sciences Citation Index - Management & Economics subset
export const CSSCI_JOURNALS = new Set([
  // 管理学
  "管理世界",
  "管理科学学报",
  "南开管理评论",
  "中国管理科学",
  "管理科学",
  "中国工业经济",
  "管理学报",
  "科学学研究",
  "科研管理",
  "研究与发展管理",
  "科学学与科学技术管理",
  "管理评论",
  "外国经济与管理",
  "管理工程学报",
  "系统工程理论与实践",
  "系统管理学报",
  "中国软科学",
  "预测",
  "系统工程",
  "运筹与管理",
  "管理现代化",
  "中国科技论坛",
  "技术经济",
  "技术经济与管理研究",
  "软科学",
  "科技进步与对策",
  "科技管理研究",

  // 经济学
  "经济研究",
  "经济学(季刊)",
  "世界经济",
  "金融研究",
  "中国社会科学",
  "会计研究",
  "审计研究",
  "数量经济技术经济研究",
  "经济科学",
  "经济理论与经济管理",
  "国际贸易问题",
  "国际经济评论",
  "世界经济文汇",
  "财贸经济",
  "财经研究",
  "经济管理",
  "经济与管理研究",
  "中国经济问题",
  "产业经济研究",
  "南方经济",
  "当代经济科学",
  "财经科学",
  "中央财经大学学报",
  "上海财经大学学报",
  "财经论丛",
  "国际商务",
  "商业经济与管理",

  // 会计/审计/财务
  "会计研究",
  "审计研究",
  "财务研究",
  "审计与经济研究",
  "中国审计评论",

  // 营销/旅游
  "旅游学刊",
  "旅游科学",
  "营销科学学报",

  // 人力资源/组织行为
  "中国人力资源开发",

  // 信息管理/图书情报
  "情报学报",
  "中国图书馆学报",
  "图书情报工作",
  "大学图书馆学报",
  "图书情报知识",
  "情报杂志",
  "图书与情报",
  "情报理论与实践",
  "情报科学",

  // 公共管理
  "中国行政管理",
  "公共管理学报",
  "公共管理与政策评论",

  // 统计学
  "统计研究",
  "数理统计与管理",
  "统计与信息论坛",
  "统计与决策",

  // 社会学
  "社会学研究",
  "社会",
  "社会科学",
  "中国社会科学",
  "学术月刊",
  "开放时代",
]);

// ─── 北大核心（管理/经济相关）──────────────────
// Peking University Chinese Core Journals - Management & Economics subset
export const PKU_CORE_JOURNALS = new Set([
  // All CSSCI journals are typically also PKU core, plus these additional ones:
  ...CSSCI_JOURNALS,

  // 额外的北大核心（不在CSSCI中）
  "现代管理科学",
  "经济问题探索",
  "经济纵横",
  "当代财经",
  "经济学家",
  "现代经济探讨",
  "经济体制改革",
  "改革",
  "价格理论与实践",
  "经济问题",
  "华东经济管理",
  "企业经济",
  "中国流通经济",
  "商业研究",
  "商业时代",
  "财会月刊",
  "财会通讯",
  "会计之友",
  "中国注册会计师",
  "国际贸易",
  "对外经贸实务",
  "现代财经",
  "生产力研究",
  "工业技术经济",
  "宏观经济研究",
  "经济与管理",
  "中国人口资源与环境",
  "中国科技论坛",
  "科学管理研究",
  "领导科学",
  "中国行政管理",
]);

// ─── JCR 分区（管理学/商学/经济学/IS 核心期刊）──────
// Journal Citation Reports quartiles
export const JCR_QUARTILES: Record<string, "Q1" | "Q2" | "Q3" | "Q4"> = {
  // === Management Q1 ===
  "academy of management journal": "Q1",
  "academy of management review": "Q1",
  "administrative science quarterly": "Q1",
  "strategic management journal": "Q1",
  "journal of management": "Q1",
  "management science": "Q1",
  "organization science": "Q1",
  "journal of management studies": "Q1",
  "journal of operations management": "Q1",
  "organizational behavior and human decision processes": "Q1",
  "journal of international business studies": "Q1",
  "leadership quarterly": "Q1",
  "journal of organizational behavior": "Q1",
  "journal of business venturing": "Q1",
  "entrepreneurship theory and practice": "Q1",
  "academy of management annals": "Q1",
  "research policy": "Q1",
  "journal of business ethics": "Q1",
  "journal of supply chain management": "Q1",
  "production and operations management": "Q1",
  "british journal of management": "Q1",
  "organization studies": "Q1",
  "human resource management": "Q1",
  "human relations": "Q1",
  "journal of world business": "Q1",
  "long range planning": "Q1",
  "journal of business research": "Q1",
  "international journal of management reviews": "Q1",
  "academy of management perspectives": "Q1",
  "academy of management learning and education": "Q1",
  "journal of product innovation management": "Q1",
  "technovation": "Q1",
  "international journal of operations and production management": "Q1",
  "omega": "Q1",

  // === Finance Q1 ===
  "journal of finance": "Q1",
  "journal of financial economics": "Q1",
  "review of financial studies": "Q1",
  "journal of financial and quantitative analysis": "Q1",
  "journal of monetary economics": "Q1",
  "review of finance": "Q1",
  "journal of corporate finance": "Q1",
  "journal of banking and finance": "Q1",
  "financial management": "Q1",
  "journal of financial intermediation": "Q1",
  "journal of financial markets": "Q1",

  // === Accounting Q1 ===
  "journal of accounting and economics": "Q1",
  "journal of accounting research": "Q1",
  "accounting review": "Q1",
  "the accounting review": "Q1",
  "review of accounting studies": "Q1",
  "contemporary accounting research": "Q1",
  "accounting organizations and society": "Q1",
  "management accounting research": "Q1",
  "auditing a journal of practice and theory": "Q1",

  // === Marketing Q1 ===
  "journal of marketing": "Q1",
  "journal of marketing research": "Q1",
  "journal of consumer research": "Q1",
  "marketing science": "Q1",
  "journal of the academy of marketing science": "Q1",
  "journal of consumer psychology": "Q1",
  "journal of retailing": "Q1",
  "international journal of research in marketing": "Q1",
  "journal of service research": "Q1",
  "journal of interactive marketing": "Q1",

  // === Information Systems Q1 ===
  "mis quarterly": "Q1",
  "information systems research": "Q1",
  "journal of management information systems": "Q1",
  "journal of the association for information systems": "Q1",
  "journal of strategic information systems": "Q1",
  "european journal of information systems": "Q1",
  "information and management": "Q1",
  "journal of information technology": "Q1",
  "decision support systems": "Q1",
  "information systems journal": "Q1",
  "government information quarterly": "Q1",
  "international journal of information management": "Q1",
  "internet research": "Q1",
  "information processing and management": "Q1",

  // === Economics Q1 ===
  "american economic review": "Q1",
  "econometrica": "Q1",
  "quarterly journal of economics": "Q1",
  "journal of political economy": "Q1",
  "review of economic studies": "Q1",
  "journal of economic theory": "Q1",
  "journal of econometrics": "Q1",
  "journal of economic literature": "Q1",
  "journal of economic perspectives": "Q1",
  "economic journal": "Q1",
  "review of economics and statistics": "Q1",
  "journal of labor economics": "Q1",
  "journal of public economics": "Q1",
  "journal of international economics": "Q1",
  "journal of development economics": "Q1",
  "journal of health economics": "Q1",

  // === Operations Research Q1 ===
  "operations research": "Q1",
  "manufacturing and service operations management": "Q1",
  "mathematics of operations research": "Q1",
  "european journal of operational research": "Q1",
  "transportation research part b": "Q1",
  "transportation science": "Q1",
  "naval research logistics": "Q1",
  "annals of operations research": "Q1",

  // === Psychology/OB Q1 ===
  "journal of applied psychology": "Q1",
  "personnel psychology": "Q1",
  "journal of vocational behavior": "Q1",
  "journal of occupational and organizational psychology": "Q1",
  "journal of occupational health psychology": "Q1",
  "journal of business and psychology": "Q1",

  // === Q2 Management/Business ===
  "group and organization management": "Q2",
  "journal of management inquiry": "Q2",
  "international journal of human resource management": "Q2",
  "asia pacific journal of management": "Q2",
  "management international review": "Q2",
  "journal of small business management": "Q2",
  "family business review": "Q2",
  "strategic entrepreneurship journal": "Q2",
  "journal of knowledge management": "Q2",
  "journal of business logistics": "Q2",
  "business strategy and the environment": "Q2",
  "corporate social responsibility and environmental management": "Q2",
  "journal of cleaner production": "Q2",
  "sustainable development": "Q2",
  "journal of engineering and technology management": "Q2",
  "r and d management": "Q2",
  "creativity and innovation management": "Q2",
  "international journal of project management": "Q2",
  "project management journal": "Q2",
  "international journal of production research": "Q2",
  "international journal of production economics": "Q2",
  "supply chain management an international journal": "Q2",
  "journal of purchasing and supply management": "Q2",
  "journal of scheduling": "Q2",
  "journal of business finance and accounting": "Q2",
  "european financial management": "Q2",
  "pacific basin finance journal": "Q2",
  "journal of international financial markets institutions and money": "Q2",
  "journal of risk and insurance": "Q2",
  "journal of advertising": "Q2",
  "journal of advertising research": "Q2",
  "psychology and marketing": "Q2",
  "journal of business to business marketing": "Q2",
  "european journal of marketing": "Q2",
  "industrial marketing management": "Q2",
  "journal of public policy and marketing": "Q2",

  // === Q3 ===
  "journal of management and governance": "Q3",
  "management decision": "Q3",
  "management learning": "Q3",
  "journal of general management": "Q3",
  "international journal of management education": "Q3",
  "chinese management studies": "Q3",
  "baltic journal of management": "Q3",
  "journal of organizational change management": "Q3",
  "benchmarking an international journal": "Q3",
  "measuring business excellence": "Q3",
  "journal of management and organization": "Q3",
};

// ─── ABDC 澳洲商学院排名（管理/商学核心期刊）──────
// Australian Business Deans Council Journal Quality List
export const ABDC_RANKINGS: Record<string, "A*" | "A" | "B" | "C"> = {
  // === A* ===
  "academy of management journal": "A*",
  "academy of management review": "A*",
  "administrative science quarterly": "A*",
  "strategic management journal": "A*",
  "management science": "A*",
  "journal of management": "A*",
  "organization science": "A*",
  "journal of management studies": "A*",
  "journal of operations management": "A*",
  "journal of international business studies": "A*",
  "organizational behavior and human decision processes": "A*",
  "leadership quarterly": "A*",
  "journal of organizational behavior": "A*",
  "journal of business venturing": "A*",
  "entrepreneurship theory and practice": "A*",
  "journal of finance": "A*",
  "journal of financial economics": "A*",
  "review of financial studies": "A*",
  "journal of accounting and economics": "A*",
  "journal of accounting research": "A*",
  "accounting review": "A*",
  "the accounting review": "A*",
  "journal of marketing": "A*",
  "journal of marketing research": "A*",
  "journal of consumer research": "A*",
  "marketing science": "A*",
  "mis quarterly": "A*",
  "information systems research": "A*",
  "operations research": "A*",
  "journal of applied psychology": "A*",
  "american economic review": "A*",
  "econometrica": "A*",
  "quarterly journal of economics": "A*",
  "journal of political economy": "A*",
  "review of economic studies": "A*",
  "academy of management annals": "A*",
  "research policy": "A*",
  "journal of business ethics": "A*",
  "production and operations management": "A*",
  "personnel psychology": "A*",
  "accounting organizations and society": "A*",
  "contemporary accounting research": "A*",
  "review of accounting studies": "A*",
  "journal of the academy of marketing science": "A*",
  "journal of consumer psychology": "A*",
  "journal of financial and quantitative analysis": "A*",
  "human resource management": "A*",
  "human relations": "A*",
  "journal of management information systems": "A*",
  "decision support systems": "A*",

  // === A ===
  "academy of management perspectives": "A",
  "academy of management learning and education": "A",
  "british journal of management": "A",
  "organization studies": "A",
  "journal of world business": "A",
  "long range planning": "A",
  "journal of business research": "A",
  "journal of product innovation management": "A",
  "technovation": "A",
  "international journal of operations and production management": "A",
  "omega": "A",
  "european journal of operational research": "A",
  "international journal of human resource management": "A",
  "asia pacific journal of management": "A",
  "management international review": "A",
  "journal of small business management": "A",
  "family business review": "A",
  "strategic entrepreneurship journal": "A",
  "journal of knowledge management": "A",
  "journal of business logistics": "A",
  "business strategy and the environment": "A",
  "journal of cleaner production": "A",
  "journal of engineering and technology management": "A",
  "r and d management": "A",
  "international journal of production research": "A",
  "international journal of production economics": "A",
  "group and organization management": "A",
  "journal of corporate finance": "A",
  "journal of banking and finance": "A",
  "european financial management": "A",
  "journal of advertising": "A",
  "psychology and marketing": "A",
  "industrial marketing management": "A",
  "european journal of marketing": "A",
  "journal of retailing": "A",
  "international journal of research in marketing": "A",
  "journal of service research": "A",
  "information and management": "A",
  "journal of strategic information systems": "A",
  "european journal of information systems": "A",
  "journal of the association for information systems": "A",
  "information systems journal": "A",
  "journal of information technology": "A",
  "government information quarterly": "A",
  "international journal of information management": "A",
  "internet research": "A",
  "management accounting research": "A",
  "auditing a journal of practice and theory": "A",
  "journal of business finance and accounting": "A",
  "corporate social responsibility and environmental management": "A",
  "international journal of management reviews": "A",
  "journal of vocational behavior": "A",
  "journal of occupational and organizational psychology": "A",
  "journal of business and psychology": "A",
  "international journal of project management": "A",
  "supply chain management an international journal": "A",
  "journal of international financial markets institutions and money": "A",
  "journal of risk and insurance": "A",
  "journal of public policy and marketing": "A",
  "management decision": "A",

  // === B ===
  "journal of management inquiry": "B",
  "management learning": "B",
  "chinese management studies": "B",
  "journal of organizational change management": "B",
  "journal of management and governance": "B",
  "journal of management and organization": "B",
  "creativity and innovation management": "B",
  "project management journal": "B",
  "journal of purchasing and supply management": "B",
  "journal of advertising research": "B",
  "journal of business to business marketing": "B",
  "baltic journal of management": "B",
  "international journal of management education": "B",
  "measuring business excellence": "B",
  "benchmarking an international journal": "B",
};

// ─── FMS 管理科学高质量期刊推荐列表 ──────────────
// Based on major management science recommendations
export const FMS_JOURNALS = new Set([
  "academy of management journal",
  "academy of management review",
  "administrative science quarterly",
  "strategic management journal",
  "management science",
  "organization science",
  "journal of management",
  "journal of management studies",
  "journal of international business studies",
  "journal of operations management",
  "organizational behavior and human decision processes",
  "journal of business venturing",
  "entrepreneurship theory and practice",
  "leadership quarterly",
  "journal of organizational behavior",
  "research policy",
  "production and operations management",
  "human relations",
  "human resource management",
  "journal of business ethics",
  "journal of world business",
  "british journal of management",
  "organization studies",
  "journal of finance",
  "journal of financial economics",
  "review of financial studies",
  "journal of accounting and economics",
  "journal of accounting research",
  "the accounting review",
  "accounting review",
  "accounting organizations and society",
  "journal of marketing",
  "journal of marketing research",
  "journal of consumer research",
  "marketing science",
  "mis quarterly",
  "information systems research",
  "operations research",
  "journal of applied psychology",
  "personnel psychology",
  "american economic review",
  "econometrica",
  "quarterly journal of economics",
  "journal of political economy",
  "review of economic studies",
  "journal of economic theory",
  "academy of management annals",
  "academy of management perspectives",
  "academy of management learning and education",
  "journal of financial and quantitative analysis",
]);

// ─── 中科院分区 三区/四区 ──────────────────────
// Extends CAS zones beyond the 一区/二区 already defined in journal-metadata.ts
export const CAS_ZONE_3 = new Set([
  // Management & Business
  "group and organization management", "management international review",
  "asia pacific journal of management", "journal of small business management",
  "family business review", "strategic entrepreneurship journal",
  "journal of knowledge management", "journal of business logistics",
  "business strategy and the environment", "journal of engineering and technology management",
  "r and d management", "creativity and innovation management",
  "international journal of project management", "corporate social responsibility and environmental management",
  "journal of management inquiry", "international journal of human resource management",
  "journal of corporate finance", "journal of banking and finance",
  "european financial management", "journal of advertising",
  "industrial marketing management", "european journal of marketing",
  "journal of information technology", "information systems journal",
  "internet research", "information processing and management",
  "journal of business finance and accounting", "auditing a journal of practice and theory",
  "management accounting research", "international journal of management reviews",
  "journal of vocational behavior", "journal of business and psychology",
  "journal of occupational and organizational psychology",
  "international journal of production research", "international journal of production economics",
  "supply chain management an international journal",
  "european journal of operational research", "omega",
  "decision support systems", "journal of strategic information systems",
  "european journal of information systems", "journal of the association for information systems",
  "government information quarterly", "international journal of information management",
  // Science
  "nature communications", "science advances", "pnas",
  "proceedings of the national academy of sciences",
  "physical review letters", "acs nano", "nano letters",
  "journal of the american chemical society",
]);

export const CAS_ZONE_4 = new Set([
  // Management & Business
  "management decision", "management learning", "journal of general management",
  "chinese management studies", "journal of organizational change management",
  "journal of management and governance", "journal of management and organization",
  "project management journal", "journal of purchasing and supply management",
  "journal of advertising research", "psychology and marketing",
  "journal of business to business marketing", "journal of public policy and marketing",
  "baltic journal of management", "benchmarking an international journal",
  "international journal of management education", "measuring business excellence",
  "journal of scheduling",
  "pacific basin finance journal", "journal of international financial markets institutions and money",
  "journal of risk and insurance",
  // More general
  "sustainability", "international journal of environmental research and public health",
  "applied sciences", "frontiers in psychology",
]);

// ─── 学术会议排名 ──────────────────────────────
// Tier: "Top" = 顶级会议, "A" = 一流会议, "B" = 优秀会议

export interface ConferenceInfo {
  tier: "Top" | "A" | "B";
  field: string;
  fullName: string;
}

export const CONFERENCE_RANKINGS: Record<string, ConferenceInfo> = {
  // === Management / Business Top Conferences ===
  "aom": { tier: "Top", field: "管理学", fullName: "Academy of Management Annual Meeting" },
  "academy of management": { tier: "Top", field: "管理学", fullName: "Academy of Management Annual Meeting" },
  "academy of management annual meeting": { tier: "Top", field: "管理学", fullName: "AOM Annual Meeting" },
  "academy of management proceedings": { tier: "Top", field: "管理学", fullName: "AOM Proceedings" },
  "ama": { tier: "Top", field: "营销", fullName: "American Marketing Association Conference" },
  "american marketing association": { tier: "Top", field: "营销", fullName: "AMA Conference" },
  "ama winter": { tier: "Top", field: "营销", fullName: "AMA Winter Academic Conference" },
  "ama summer": { tier: "Top", field: "营销", fullName: "AMA Summer Academic Conference" },
  "sms": { tier: "Top", field: "战略", fullName: "Strategic Management Society Annual Conference" },
  "strategic management society": { tier: "Top", field: "战略", fullName: "SMS Annual Conference" },
  "aib": { tier: "Top", field: "国际商务", fullName: "Academy of International Business Annual Meeting" },
  "academy of international business": { tier: "Top", field: "国际商务", fullName: "AIB Annual Meeting" },
  "informs": { tier: "Top", field: "运营管理", fullName: "INFORMS Annual Meeting" },
  "afa": { tier: "Top", field: "金融", fullName: "American Finance Association Annual Meeting" },
  "american finance association": { tier: "Top", field: "金融", fullName: "AFA Annual Meeting" },
  "aaa": { tier: "Top", field: "会计", fullName: "American Accounting Association Annual Meeting" },
  "american accounting association": { tier: "Top", field: "会计", fullName: "AAA Annual Meeting" },

  // === Management A-tier Conferences ===
  "euram": { tier: "A", field: "管理学", fullName: "European Academy of Management Conference" },
  "bam": { tier: "A", field: "管理学", fullName: "British Academy of Management Conference" },
  "egos": { tier: "A", field: "组织研究", fullName: "European Group for Organizational Studies Colloquium" },
  "iacm": { tier: "A", field: "冲突管理", fullName: "International Association for Conflict Management" },
  "siop": { tier: "A", field: "组织心理", fullName: "Society for Industrial and Organizational Psychology" },
  "babson": { tier: "A", field: "创业", fullName: "Babson College Entrepreneurship Research Conference" },
  "acr": { tier: "A", field: "消费者研究", fullName: "Association for Consumer Research Conference" },
  "emac": { tier: "A", field: "营销", fullName: "European Marketing Academy Conference" },

  // === AI / CS Top Conferences (CCF-A already in CCF_RANKINGS, these add conference-level info) ===
  "neurips": { tier: "Top", field: "AI/ML", fullName: "Conference on Neural Information Processing Systems" },
  "nips": { tier: "Top", field: "AI/ML", fullName: "Conference on Neural Information Processing Systems" },
  "icml": { tier: "Top", field: "AI/ML", fullName: "International Conference on Machine Learning" },
  "iclr": { tier: "Top", field: "AI/ML", fullName: "International Conference on Learning Representations" },
  "aaai": { tier: "Top", field: "AI", fullName: "AAAI Conference on Artificial Intelligence" },
  "ijcai": { tier: "Top", field: "AI", fullName: "International Joint Conference on Artificial Intelligence" },
  "cvpr": { tier: "Top", field: "计算机视觉", fullName: "IEEE/CVF Conference on Computer Vision and Pattern Recognition" },
  "iccv": { tier: "Top", field: "计算机视觉", fullName: "IEEE International Conference on Computer Vision" },
  "acl": { tier: "Top", field: "NLP", fullName: "Annual Meeting of the Association for Computational Linguistics" },
  "emnlp": { tier: "A", field: "NLP", fullName: "Conference on Empirical Methods in Natural Language Processing" },
  "naacl": { tier: "A", field: "NLP", fullName: "Conference of the North American Chapter of the ACL" },
  "kdd": { tier: "Top", field: "数据挖掘", fullName: "ACM SIGKDD Conference on Knowledge Discovery and Data Mining" },
  "sigkdd": { tier: "Top", field: "数据挖掘", fullName: "ACM SIGKDD" },
  "www": { tier: "Top", field: "Web", fullName: "The Web Conference" },
  "sigir": { tier: "Top", field: "信息检索", fullName: "ACM SIGIR Conference on Research and Development in IR" },
  "chi": { tier: "Top", field: "HCI", fullName: "ACM CHI Conference on Human Factors in Computing Systems" },
  "cscw": { tier: "A", field: "协同工作", fullName: "ACM Conference on Computer-Supported Cooperative Work" },
  "icis": { tier: "Top", field: "信息系统", fullName: "International Conference on Information Systems" },
  "ecis": { tier: "A", field: "信息系统", fullName: "European Conference on Information Systems" },
  "amcis": { tier: "A", field: "信息系统", fullName: "Americas Conference on Information Systems" },
  "pacis": { tier: "A", field: "信息系统", fullName: "Pacific Asia Conference on Information Systems" },
  "hicss": { tier: "A", field: "信息系统", fullName: "Hawaii International Conference on System Sciences" },
  "wsdm": { tier: "A", field: "Web搜索", fullName: "ACM International Conference on Web Search and Data Mining" },
  "recsys": { tier: "A", field: "推荐系统", fullName: "ACM Conference on Recommender Systems" },
  "eccv": { tier: "A", field: "计算机视觉", fullName: "European Conference on Computer Vision" },
  "coling": { tier: "B", field: "NLP", fullName: "International Conference on Computational Linguistics" },
  "aistats": { tier: "A", field: "AI/统计", fullName: "International Conference on AI and Statistics" },

  // === arXiv as preprint venue ===
  "arxiv": { tier: "B", field: "预印本", fullName: "arXiv Preprint Server" },
  "ssrn": { tier: "B", field: "预印本", fullName: "Social Science Research Network" },
};
