// ABS Academic Journal Guide 2024 - Complete (1635 journals)
// Source: journalranking.org (Chartered ABS)
export const ABS_RATINGS: Record<string, string> = {
  "4or": "2",
  "abacus": "3",
  "academia revista latinoamericana de administracion": "1",
  "academy of management annals": "4*",
  "academy of management discoveries": "3",
  "academy of management journal": "4*",
  "academy of management learning and education": "4*",
  "academy of management perspectives": "4",
  "academy of management review": "4*",
  "academy of marketing science review": "2",
  "accident analysis and prevention": "3",
  "accounting and business research": "3",
  "accounting and finance": "2",
  "accounting and the public interest": "2",
  "accounting education": "2",
  "accounting forum": "3",
  "accounting historians journal": "2",
  "accounting history": "2",
  "accounting history review": "2",
  "accounting horizons": "3",
  "accounting in europe": "2",
  "accounting research journal": "2",
  "accounting review": "4*",
  "accounting, auditing and accountability journal": "3",
  "accounting, economics and law: a convivium": "2",
  "accounting, finance & governance review": "1",
  "accounting, organizations and society": "4*",
  "acm transactions on modeling and computer simulation": "3",
  "acta commercii": "1",
  "action learning: research and practice": "1",
  "action research": "1",
  "active learning in higher education": "1",
  "administration and society": "2",
  "administrative science quarterly": "4*",
  "administrative theory and praxis": "1",
  "advances in accounting": "2",
  "advances in accounting behavioral research": "2",
  "advances in accounting education: teaching and curriculum innovations": "1",
  "advances in austrian economics": "1",
  "advances in consumer research": "2",
  "advances in developing human resources": "2",
  "advances in econometrics": "2",
  "advances in environmental accounting and management": "1",
  "advances in hospitality and leisure": "1",
  "advances in industrial and labor relations": "1",
  "advances in management accounting": "2",
  "advances in public interest accounting": "1",
  "advances in strategic management": "2",
  "advances in taxation": "2",
  "africa journal of management": "2",
  "african affairs": "3",
  "african evaluation journal": "1",
  "african finance journal": "1",
  "agrekon": "1",
  "agricultural and resource economics review": "1",
  "agricultural economics (united kingdom)": "2",
  "agricultural finance review": "1",
  "ais transactions on human-computer interaction": "2",
  "american behavioral scientist": "1",
  "american economic journal: applied economics": "4",
  "american economic journal: economic policy": "3",
  "american economic journal: macroeconomics": "4",
  "american economic journal: microeconomics": "3",
  "american economic review": "4*",
  "american economic review: insights": "3",
  "american journal of agricultural economics": "3",
  "american journal of business": "1",
  "american journal of economics and sociology": "2",
  "american journal of psychology": "1",
  "american journal of sociology": "4*",
  "american law and economics review": "2",
  "american review of public administration": "3",
  "american sociological review": "4*",
  "anatolia: an international journal of tourism and hospitality research": "1",
  "annals of actuarial science": "1",
  "annals of applied statistics": "2",
  "annals of economics and finance": "2",
  "annals of economics and statistics": "1",
  "annals of finance": "2",
  "annals of leisure research": "2",
  "annals of operations research": "3",
  "annals of public and cooperative economics": "2",
  "annals of regional science": "2",
  "annals of statistics": "4*",
  "annals of tourism research": "4",
  "annals of work exposures and health": "1",
  "annual review of economics": "3",
  "annual review of financial economics": "3",
  "annual review of information science and technology": "2",
  "annual review of psychology": "4",
  "annual review of resource economics": "2",
  "annual review of sociology": "4*",
  "antipode": "3",
  "applied cognitive psychology": "2",
  "applied economic perspectives and policy": "2",
  "applied economics": "2",
  "applied economics letters": "1",
  "applied ergonomics": "3",
  "applied mathematical finance": "2",
  "applied psychological measurement": "2",
  "applied psychology": "3",
  "applied psychology: health and well-being": "2",
  "area": "1",
  "asia europe journal": "1",
  "asia pacific business review": "2",
  "asia pacific journal of human resources": "2",
  "asia pacific journal of management": "3",
  "asia pacific journal of marketing and logistics": "1",
  "asia pacific journal of tourism research": "1",
  "asia-pacific financial markets": "2",
  "asia-pacific journal of accounting and economics": "2",
  "asia-pacific journal of business administration": "1",
  "asia-pacific journal of operational research": "1",
  "asian business and management": "2",
  "asian economic journal": "1",
  "asian economic papers": "1",
  "asian journal of management cases": "1",
  "asian journal of technology innovation": "1",
  "asian review of accounting": "2",
  "aslib journal of information management": "1",
  "astin bulletin": "2",
  "ata journal of legal tax research": "1",
  "atlantic economic journal": "1",
  "auditing": "3",
  "australasian accounting, business and finance journal": "1",
  "australasian journal of information systems": "1",
  "australasian marketing journal": "1",
  "australian accounting review": "2",
  "australian economic history review": "2",
  "australian economic papers": "1",
  "australian economic review": "1",
  "australian journal of agricultural and resource economics": "2",
  "australian journal of labour economics": "1",
  "australian journal of management": "2",
  "australian journal of psychology": "1",
  "australian journal of public administration": "2",
  "b.e. journal of economic analysis and policy": "2",
  "b.e. journal of macroeconomics": "2",
  "b.e. journal of theoretical economics": "2",
  "baltic journal of economics": "1",
  "baltic journal of management": "1",
  "bancaria the journal of the italian banking association": "1",
  "basic and applied social psychology": "1",
  "behavioral and brain sciences": "4",
  "behavioral research in accounting": "3",
  "behaviour and information technology": "2",
  "behavioural public policy": "1",
  "benchmarking": "1",
  "biometrika": "4",
  "british accounting review": "3",
  "british actuarial journal": "1",
  "british educational research journal": "2",
  "british food journal": "1",
  "british journal of educational technology": "2",
  "british journal of guidance and counselling": "2",
  "british journal of health care management": "1",
  "british journal of industrial relations": "4",
  "british journal of management": "4",
  "british journal of psychology": "3",
  "british journal of social psychology": "3",
  "british journal of sociology": "3",
  "british tax review": "3",
  "brookings papers on economic activity": "3",
  "brq business research quarterly": "2",
  "building research and information": "2",
  "built environment project and asset management": "1",
  "bulletin of economic research": "2",
  "bulletin of indonesian economic studies": "1",
  "business & professional ethics journal": "1",
  "business and human rights journal": "1",
  "business and politics": "2",
  "business and society": "3",
  "business economics": "1",
  "business ethics quarterly": "3",
  "business history": "4",
  "business history review": "4",
  "business horizons": "2",
  "business perspectives and research": "1",
  "business process management journal": "2",
  "business strategy and the environment": "3",
  "california management review": "3",
  "cambridge journal of economics": "3",
  "cambridge journal of regions, economy and society": "3",
  "canadian journal of administrative sciences": "2",
  "canadian journal of agricultural economics": "2",
  "canadian journal of behavioural science": "1",
  "canadian journal of economics": "3",
  "canadian psychology": "1",
  "capital and class": "2",
  "career development international": "2",
  "career development quarterly": "2",
  "case journal": "1",
  "central european journal of operations research": "1",
  "cesifo economic studies": "2",
  "china agricultural economic review": "1",
  "china and world economy": "1",
  "china economic journal": "1",
  "china economic review": "2",
  "china finance review international": "1",
  "china journal of accounting research": "2",
  "china journal of accounting studies": "1",
  "china quarterly": "2",
  "chinese management studies": "1",
  "cities": "2",
  "cliometrica": "2",
  "coaching": "1",
  "cogent business and management": "1",
  "cogent economics and finance": "1",
  "cognition": "4",
  "cognition, technology and work": "2",
  "cognitive research: principles and implications": "2",
  "cognitive science": "3",
  "communications of the acm": "2",
  "communications of the association for information systems": "2",
  "community, work and family": "1",
  "comparative economic studies": "1",
  "competition and change": "2",
  "competitiveness review": "1",
  "comptabilite controle audit": "1",
  "computational economics": "1",
  "computational management science": "1",
  "computational optimization and applications": "3",
  "computational statistics": "2",
  "computational statistics and data analysis": "3",
  "computer journal": "2",
  "computer supported cooperative work": "2",
  "computers and industrial engineering": "2",
  "computers and operations research": "3",
  "computers in human behavior": "2",
  "computers in industry": "3",
  "concurrent engineering research and applications": "1",
  "constitutional political economy": "1",
  "construction management and economics": "2",
  "consumption markets and culture": "2",
  "contemporary accounting research": "4",
  "contemporary economic policy": "2",
  "contributions to political economy": "2",
  "cornell hospitality quarterly": "2",
  "corporate communications": "1",
  "corporate governance (bingley)": "2",
  "corporate governance: an international review": "3",
  "corporate reputation review": "1",
  "corporate social responsibility and environmental management": "1",
  "creativity and innovation management": "2",
  "creativity research journal": "2",
  "critical finance review": "1",
  "critical perspectives on accounting": "3",
  "critical perspectives on international business": "2",
  "critical social policy": "2",
  "cross cultural and strategic management": "2",
  "culture and organization": "2",
  "current directions in psychological science": "4",
  "current issues in auditing": "2",
  "current issues in tourism": "2",
  "current psychology": "1",
  "current sociology": "2",
  "cybernetics and systems": "1",
  "de economist": "1",
  "decision": "2",
  "decision analysis": "1",
  "decision sciences": "3",
  "decision sciences journal of innovative education": "1",
  "decision support systems": "3",
  "decisions in economics and finance": "1",
  "defence and peace economics": "2",
  "development and change": "3",
  "digital policy, regulation and governance": "1",
  "disability and rehabilitation": "1",
  "discrete applied mathematics": "2",
  "discrete optimization": "2",
  "dynamic games and applications": "1",
  "e-service journal": "1",
  "eastern economic journal": "1",
  "eastern european economics": "1",
  "ecological economics": "3",
  "econ journal watch": "2",
  "econometric reviews": "3",
  "econometric theory": "4",
  "econometrica": "4*",
  "econometrics": "1",
  "econometrics journal": "3",
  "economic analysis and policy": "1",
  "economic and business review": "1",
  "economic and industrial democracy": "3",
  "economic and labour relations review": "1",
  "economic and social review": "1",
  "economic development and cultural change": "3",
  "economic geography": "4",
  "economic history review": "4",
  "economic inquiry": "3",
  "economic issues": "1",
  "economic journal": "4",
  "economic modelling": "2",
  "economic notes": "1",
  "economic policy": "3",
  "economic record": "2",
  "economic systems": "2",
  "economic systems research": "2",
  "economic theory": "3",
  "economic theory bulletin": "2",
  "economica": "3",
  "economics and business letters": "1",
  "economics and human biology": "2",
  "economics and philosophy": "2",
  "economics and politics": "2",
  "economics and sociology": "1",
  "economics letters": "3",
  "economics of education review": "2",
  "economics of energy and environmental policy": "1",
  "economics of governance": "1",
  "economics of innovation and new technology": "2",
  "economics of transportation": "1",
  "economies": "1",
  "economists' voice": "1",
  "economy and society": "3",
  "edpacs": "1",
  "education and training": "1",
  "education economics": "1",
  "educational management administration and leadership": "2",
  "electoral studies": "3",
  "electronic commerce research": "2",
  "electronic commerce research and applications": "2",
  "electronic journal of e-learning": "1",
  "electronic markets": "2",
  "emerald emerging markets case studies": "1",
  "emerging markets finance and trade": "2",
  "emerging markets review": "2",
  "empirica": "1",
  "empirical economics": "2",
  "employee relations": "2",
  "energy economics": "3",
  "energy journal": "3",
  "energy policy": "2",
  "engineering optimization": "2",
  "engineering, construction and architectural management": "1",
  "enterprise and society": "3",
  "enterprise information systems": "2",
  "entrepreneurship and regional development": "3",
  "entrepreneurship research journal": "2",
  "entrepreneurship theory and practice": "4*",
  "entreprises et histoire": "2",
  "environment and development economics": "2",
  "environment and planning a": "3",
  "environment and planning d: society and space": "4",
  "environmental and resource economics": "3",
  "environmental economics": "1",
  "environmental economics and policy studies": "1",
  "environmental management": "2",
  "environmental science & technology": "3",
  "environmental science and policy": "3",
  "ephemera: critical dialogues on organization": "1",
  "equality, diversity and inclusion: an international journal": "2",
  "ergonomics": "3",
  "essays in economic and business history": "2",
  "ethics and information technology": "1",
  "ethnic and racial studies": "1",
  "eurasian business review": "2",
  "eurasian economic review": "1",
  "eurasian geography and economics": "2",
  "euromed journal of business": "2",
  "europe-asia studies": "2",
  "european accounting review": "3",
  "european business review": "2",
  "european economic review": "3",
  "european financial management": "3",
  "european journal of economics and economic policies: intervention": "1",
  "european journal of finance": "3",
  "european journal of health economics": "2",
  "european journal of industrial engineering": "2",
  "european journal of industrial relations": "3",
  "european journal of information systems": "4",
  "european journal of innovation management": "1",
  "european journal of international management": "2",
  "european journal of law and economics": "1",
  "european journal of marketing": "3",
  "european journal of operational research": "4",
  "european journal of political economy": "2",
  "european journal of social psychology": "3",
  "european journal of the history of economic thought": "2",
  "european journal of training and development": "1",
  "european journal of women's studies": "2",
  "european journal of work and organizational psychology": "3",
  "european management journal": "2",
  "european management review": "3",
  "european planning studies": "2",
  "european psychologist": "1",
  "european review of agricultural economics": "3",
  "european review of economic history": "3",
  "european sociological review": "3",
  "european sport management quarterly": "3",
  "european urban and regional studies": "3",
  "european work and organizational psychology in practice": "1",
  "evaluation": "2",
  "event management": "2",
  "evidence and policy": "2",
  "evidence-based hrm": "1",
  "evolutionary computation": "3",
  "experimental economics": "3",
  "expert systems": "2",
  "expert systems with applications": "1",
  "explorations in economic history": "3",
  "facilities": "1",
  "family business review": "3",
  "feminist economics": "2",
  "feminist review": "2",
  "fiib business review": "1",
  "finance": "1",
  "finance and stochastics": "3",
  "finance research letters": "2",
  "financial accountability and management": "3",
  "financial analysts journal": "3",
  "financial history review": "2",
  "financial management": "3",
  "financial markets and portfolio management": "2",
  "financial markets, institutions and instruments": "3",
  "financial review": "3",
  "financial services review": "1",
  "finanzarchiv": "1",
  "fiscal studies": "2",
  "flexible services and manufacturing journal": "1",
  "food policy": "3",
  "foreign trade review": "1",
  "foresight": "1",
  "forum for health economics and policy": "1",
  "foundations and trends in accounting": "3",
  "foundations and trends in econometrics": "1",
  "foundations and trends in finance": "2",
  "foundations and trends in technology, information and operations management": "1",
  "futures": "2",
  "fuzzy optimization and decision making": "3",
  "games": "1",
  "games and economic behavior": "3",
  "gedrag en organisatie": "1",
  "gender and society": "3",
  "gender in management: an international journal": "1",
  "gender, work and organization": "3",
  "geneva papers on risk and insurance: issues and practice": "2",
  "geneva risk and insurance review": "2",
  "geoforum": "2",
  "geographical journal": "1",
  "german economic review": "2",
  "global business and economics review": "1",
  "global business review": "1",
  "global economic review": "1",
  "global economy journal": "1",
  "global environmental change": "3",
  "global finance journal": "2",
  "global journal of flexible systems management": "2",
  "global networks": "3",
  "global strategy journal": "4",
  "governance": "4",
  "government information quarterly": "3",
  "group and organization management": "3",
  "group decision and negotiation": "2",
  "group dynamics": "2",
  "group processes and intergroup relations": "2",
  "growth and change": "2",
  "harvard business review": "3",
  "health care management review": "2",
  "health care management science": "2",
  "health economics (united kingdom)": "3",
  "health information and libraries journal": "2",
  "health marketing quarterly": "1",
  "health policy": "2",
  "health services management research": "1",
  "health services research": "3",
  "health systems": "2",
  "higher education": "2",
  "higher education policy": "2",
  "higher education quarterly": "2",
  "higher education, skills and work-based learning": "1",
  "historical studies in industrial relations": "1",
  "history of political economy": "2",
  "hospitality and society": "2",
  "human factors": "3",
  "human factors and ergonomics in manufacturing": "1",
  "human organization": "2",
  "human performance": "3",
  "human relations": "4",
  "human resource development international": "2",
  "human resource development quarterly": "2",
  "human resource development review": "2",
  "human resource management (usa)": "4",
  "human resource management journal (uk)": "4*",
  "human resource management review": "3",
  "human-computer interaction": "1",
  "ieee transactions on cybernetics": "3",
  "ieee transactions on engineering management": "3",
  "ieee transactions on evolutionary computation": "4",
  "ieee transactions on systems, man, and cybernetics: systems": "3",
  "iim kozhikode society & management review": "2",
  "ilr review": "3",
  "ima journal of management mathematics": "2",
  "imf economic review": "3",
  "indian journal of labour economics": "1",
  "industrial and commercial training": "1",
  "industrial and corporate change": "3",
  "industrial and organizational psychology": "1",
  "industrial law journal": "3",
  "industrial management and data systems": "2",
  "industrial marketing management": "3",
  "industrial relations": "4",
  "industrial relations journal": "3",
  "industrielle beziehungen": "2",
  "industry and higher education": "1",
  "industry and innovation": "3",
  "information and computer security": "1",
  "information and management": "3",
  "information and organization": "3",
  "information communication and society": "2",
  "information economics and policy": "2",
  "information processing and management": "2",
  "information research": "1",
  "information resources management journal": "1",
  "information society": "3",
  "information systems and e-business management": "2",
  "information systems frontiers": "3",
  "information systems journal": "4",
  "information systems management": "2",
  "information systems research": "4*",
  "information technology and management": "1",
  "information technology and people": "3",
  "information technology for development": "2",
  "informs journal on computing": "3",
  "informs transactions on education": "2",
  "innovation: organization & management": "2",
  "innovations in education and teaching international": "2",
  "insurance: mathematics and economics": "3",
  "intelligent systems in accounting, finance and management": "1",
  "interacting with computers": "2",
  "interdisciplinary journal of economics and business law": "1",
  "intereconomics": "1",
  "international advances in economic research": "1",
  "international archives of occupational and environmental health": "2",
  "international business review": "3",
  "international economic journal": "1",
  "international economic review": "4",
  "international entrepreneurship and management journal": "1",
  "international game theory review": "1",
  "international hospitality review": "1",
  "international journal for educational and vocational guidance": "1",
  "international journal of accounting": "3",
  "international journal of accounting and information management": "2",
  "international journal of accounting information systems": "2",
  "international journal of accounting, auditing and performance evaluation": "2",
  "international journal of advertising": "2",
  "international journal of agile systems and management": "1",
  "international journal of arts management": "1",
  "international journal of auditing": "2",
  "international journal of bank marketing": "1",
  "international journal of banking, accounting and finance": "2",
  "international journal of business and emerging markets": "1",
  "international journal of business and systems research": "1",
  "international journal of business competition and growth": "1",
  "international journal of business environment": "1",
  "international journal of business excellence": "1",
  "international journal of business governance and ethics": "2",
  "international journal of business information systems": "1",
  "international journal of business innovation and research": "1",
  "international journal of business performance and supply chain modelling": "1",
  "international journal of business performance management": "1",
  "international journal of business process integration and management": "1",
  "international journal of central banking": "3",
  "international journal of comparative labour law and industrial relations": "1",
  "international journal of computational economics and econometrics": "1",
  "international journal of computer integrated manufacturing": "2",
  "international journal of conflict management": "2",
  "international journal of construction management": "1",
  "international journal of consumer studies": "2",
  "international journal of contemporary hospitality management": "3",
  "international journal of contemporary management": "1",
  "international journal of critical accounting": "1",
  "international journal of cross cultural management": "1",
  "international journal of culture, tourism and hospitality research": "1",
  "international journal of data analysis techniques and strategies": "1",
  "international journal of development issues": "2",
  "international journal of digital strategy, governance, and business transformation": "1",
  "international journal of disclosure and governance": "2",
  "international journal of e-business research": "1",
  "international journal of ecological economics and statistics": "1",
  "international journal of economic theory": "2",
  "international journal of educational management": "1",
  "international journal of electronic commerce": "3",
  "international journal of emergency services": "2",
  "international journal of emerging markets": "1",
  "international journal of employment studies": "1",
  "international journal of energy sector management": "1",
  "international journal of engineering business management": "1",
  "international journal of enterprise information systems": "1",
  "international journal of enterprise network management": "1",
  "international journal of entrepreneurial behaviour and research": "3",
  "international journal of entrepreneurial venturing": "1",
  "international journal of entrepreneurship and innovation": "2",
  "international journal of entrepreneurship and innovation management": "1",
  "international journal of entrepreneurship and small business": "2",
  "international journal of event and festival management": "1",
  "international journal of evidence based coaching and mentoring": "1",
  "international journal of export marketing": "1",
  "international journal of finance and economics": "3",
  "international journal of forecasting": "3",
  "international journal of foresight and innovation policy": "1",
  "international journal of game theory": "2",
  "international journal of gender and entrepreneurship": "2",
  "international journal of general systems": "1",
  "international journal of globalisation and small business": "1",
  "international journal of green energy": "2",
  "international journal of happiness and development": "1",
  "international journal of health care quality assurance": "1",
  "international journal of health economics and management": "2",
  "international journal of health governance": "1",
  "international journal of healthcare technology and management": "1",
  "international journal of heritage studies": "1",
  "international journal of hospitality and tourism administration": "1",
  "international journal of hospitality management": "3",
  "international journal of housing markets and analysis": "1",
  "international journal of human computer studies": "2",
  "international journal of human resource management": "3",
  "international journal of indian culture and business management": "1",
  "international journal of industrial and systems engineering": "1",
  "international journal of industrial engineering and management": "1",
  "international journal of industrial ergonomics": "2",
  "international journal of industrial organization": "3",
  "international journal of information management": "2",
  "international journal of information systems and change management": "1",
  "international journal of information systems and supply chain management": "1",
  "international journal of information systems in the service sector": "1",
  "international journal of information technology and management": "1",
  "international journal of innovation and sustainable development": "1",
  "international journal of innovation and technology management": "1",
  "international journal of innovation management": "2",
  "international journal of innovation science": "1",
  "international journal of integrated supply management": "1",
  "international journal of intercultural relations": "1",
  "international journal of internet manufacturing and services": "1",
  "international journal of internet marketing and advertising": "1",
  "international journal of islamic and middle eastern finance and management": "1",
  "international journal of knowledge management": "1",
  "international journal of knowledge management studies": "1",
  "international journal of knowledge-based development": "1",
  "international journal of law, crime and justice": "1",
  "international journal of lean six sigma": "1",
  "international journal of learning and intellectual capital": "1",
  "international journal of logistics management": "1",
  "international journal of logistics research and applications": "1",
  "international journal of logistics systems and management": "1",
  "international journal of management and decision making": "1",
  "international journal of management and enterprise development": "1",
  "international journal of management concepts and philosophy": "1",
  "international journal of management development": "1",
  "international journal of management education": "1",
  "international journal of management practice": "1",
  "international journal of management reviews": "3",
  "international journal of management, economics and social sciences": "1",
  "international journal of managerial and financial accounting": "2",
  "international journal of managerial finance": "2",
  "international journal of managing projects in business": "1",
  "international journal of manpower": "2",
  "international journal of market research": "2",
  "international journal of mathematics in operational research": "1",
  "international journal of occupational safety and ergonomics": "1",
  "international journal of operational research": "1",
  "international journal of operations and production management": "4",
  "international journal of operations and quantitative management": "1",
  "international journal of organization theory and behavior": "1",
  "international journal of organizational analysis": "1",
  "international journal of physical distribution and logistics management": "2",
  "international journal of political economy": "1",
  "international journal of procurement management": "1",
  "international journal of product development": "1",
  "international journal of production economics": "3",
  "international journal of production research": "3",
  "international journal of productivity and performance management": "1",
  "international journal of productivity and quality management": "1",
  "international journal of project management": "2",
  "international journal of project organisation and management": "1",
  "international journal of psychology": "1",
  "international journal of public administration": "2",
  "international journal of public sector management": "1",
  "international journal of quality and reliability management": "2",
  "international journal of quality and service sciences": "1",
  "international journal of rehabilitation research": "3",
  "international journal of research in marketing": "4",
  "international journal of retail and distribution management": "2",
  "international journal of selection and assessment": "2",
  "international journal of services and operations management": "1",
  "international journal of services operations and informatics": "1",
  "international journal of shipping and transport logistics": "1",
  "international journal of social economics": "1",
  "international journal of sociology and social policy": "1",
  "international journal of sport and society": "1",
  "international journal of sport finance": "1",
  "international journal of sport management": "1",
  "international journal of sport management and marketing": "1",
  "international journal of sport policy and politics": "1",
  "international journal of sports marketing and sponsorship": "1",
  "international journal of strategic decision sciences": "1",
  "international journal of strategic property management": "2",
  "international journal of stress management": "2",
  "international journal of teaching and case studies": "1",
  "international journal of technology and globalisation": "1",
  "international journal of technology intelligence and planning": "1",
  "international journal of technology management": "2",
  "international journal of technology management and sustainable development": "1",
  "international journal of technology marketing": "1",
  "international journal of technology transfer and commercialisation": "1",
  "international journal of technology, policy and management": "1",
  "international journal of the digital human": "1",
  "international journal of the economics of business": "2",
  "international journal of theoretical and applied finance": "2",
  "international journal of tourism research": "2",
  "international journal of training and development": "2",
  "international journal of urban and regional research": "2",
  "international journal of value chain management": "1",
  "international journal of web information systems": "1",
  "international labour review": "2",
  "international marketing review": "3",
  "international migration review": "1",
  "international negotiation": "1",
  "international public management journal": "3",
  "international review of administrative sciences": "3",
  "international review of applied economics": "1",
  "international review of economics and finance": "2",
  "international review of entrepreneurship": "2",
  "international review of environmental and resource economics": "2",
  "international review of financial analysis": "3",
  "international review of law and economics": "2",
  "international review of public administration": "1",
  "international review of retail, distribution and consumer research": "1",
  "international review on public and non-profit marketing": "1",
  "international small business journal": "3",
  "international sociology": "2",
  "international statistical review": "3",
  "international studies of management and organization": "2",
  "international tax and public finance": "2",
  "international trade journal": "1",
  "international transactions in operational research": "1",
  "internet research": "3",
  "investment analysts journal": "1",
  "iranian journal of management studies": "1",
  "irish economic and social history": "1",
  "irish journal of management": "1",
  "issues in accounting education": "2",
  "jahrbucher fur nationalokonomie und statistik": "1",
  "japan and the world economy": "1",
  "japanese economic review": "1",
  "japanese psychological research": "1",
  "journal for advancement of marketing education": "1",
  "journal for global business advancement": "1",
  "journal for international business and entrepreneurship development": "1",
  "journal for labour market research": "1",
  "journal of accounting and economics": "4*",
  "journal of accounting and management information systems": "1",
  "journal of accounting and organizational change": "2",
  "journal of accounting and public policy": "3",
  "journal of accounting and taxation": "1",
  "journal of accounting education": "2",
  "journal of accounting in emerging economies": "2",
  "journal of accounting literature": "3",
  "journal of accounting research": "4*",
  "journal of accounting, auditing and finance": "3",
  "journal of advertising": "3",
  "journal of advertising education": "1",
  "journal of advertising research": "3",
  "journal of african business": "1",
  "journal of african economies": "2",
  "journal of agrarian change": "2",
  "journal of agricultural & applied economics": "1",
  "journal of agricultural and food industrial organization": "1",
  "journal of agricultural and resource economics": "2",
  "journal of agricultural economics": "3",
  "journal of air transport management": "1",
  "journal of alternative investments": "2",
  "journal of applied accounting research": "2",
  "journal of applied corporate finance": "1",
  "journal of applied econometrics": "3",
  "journal of applied economics": "1",
  "journal of applied probability": "2",
  "journal of applied psychology": "4*",
  "journal of applied social psychology": "2",
  "journal of applied statistics": "2",
  "journal of asia business studies": "1",
  "journal of asia-pacific business": "1",
  "journal of asian economics": "1",
  "journal of asset management": "2",
  "journal of banking and finance": "3",
  "journal of banking regulation": "2",
  "journal of behavioral and experimental economics": "2",
  "journal of behavioral and experimental finance": "1",
  "journal of behavioral decision making": "3",
  "journal of behavioral finance": "2",
  "journal of bioeconomics": "1",
  "journal of brand management": "2",
  "journal of business and economic statistics": "4",
  "journal of business and industrial marketing": "2",
  "journal of business and psychology": "3",
  "journal of business economics": "2",
  "journal of business economics and management": "2",
  "journal of business ethics": "3",
  "journal of business ethics education": "1",
  "journal of business finance and accounting": "3",
  "journal of business law": "2",
  "journal of business logistics": "3",
  "journal of business models": "1",
  "journal of business research": "3",
  "journal of business strategy": "1",
  "journal of business venturing": "4*",
  "journal of business venturing insights": "2",
  "journal of business-to-business marketing": "1",
  "journal of career assessment": "2",
  "journal of career development": "1",
  "journal of change management": "1",
  "journal of china tourism research": "1",
  "journal of chinese economic and business studies": "1",
  "journal of choice modelling": "1",
  "journal of cleaner production": "1",
  "journal of cognitive engineering and decision making": "2",
  "journal of combinatorial optimization": "2",
  "journal of commodity markets": "3",
  "journal of common market studies": "3",
  "journal of communication management": "1",
  "journal of community psychology": "2",
  "journal of comparative economics": "3",
  "journal of computational and graphical statistics": "3",
  "journal of computational finance": "1",
  "journal of computer information systems": "2",
  "journal of computer-mediated communication": "3",
  "journal of conflict resolution": "3",
  "journal of construction engineering and management - asce": "2",
  "journal of constructivist psychology": "1",
  "journal of consumer affairs": "1",
  "journal of consumer behaviour": "2",
  "journal of consumer marketing": "1",
  "journal of consumer policy": "2",
  "journal of consumer psychology": "4*",
  "journal of consumer research": "4*",
  "journal of contemporary accounting and economics": "2",
  "journal of contemporary administration": "1",
  "journal of convention and event tourism": "1",
  "journal of corporate finance": "4",
  "journal of corporate real estate": "1",
  "journal of creating value": "1",
  "journal of credit risk": "1",
  "journal of cross-cultural psychology": "3",
  "journal of cultural economics": "2",
  "journal of cultural economy": "3",
  "journal of current issues and research in advertising": "1",
  "journal of database management": "1",
  "journal of decision systems": "1",
  "journal of derivatives": "2",
  "journal of destination marketing and management": "1",
  "journal of developing areas": "1",
  "journal of development economics": "3",
  "journal of development studies": "3",
  "journal of documentation": "2",
  "journal of east european management studies": "1",
  "journal of east-west business": "1",
  "journal of econometric methods": "1",
  "journal of econometrics": "4",
  "journal of economic behavior and organization": "3",
  "journal of economic dynamics and control": "3",
  "journal of economic education": "1",
  "journal of economic geography": "4",
  "journal of economic growth": "3",
  "journal of economic history": "3",
  "journal of economic inequality": "2",
  "journal of economic integration": "1",
  "journal of economic interaction and coordination": "1",
  "journal of economic issues": "2",
  "journal of economic literature": "4",
  "journal of economic methodology": "2",
  "journal of economic perspectives": "4",
  "journal of economic policy reform": "1",
  "journal of economic psychology": "2",
  "journal of economic studies": "2",
  "journal of economic surveys": "2",
  "journal of economic theory": "4",
  "journal of economics and business": "2",
  "journal of economics and management strategy": "2",
  "journal of economics/ zeitschrift fur nationalokonomie": "2",
  "journal of ecotourism": "1",
  "journal of education and work": "2",
  "journal of education policy": "2",
  "journal of educational administration": "1",
  "journal of electronic commerce in organizations": "1",
  "journal of electronic commerce research": "1",
  "journal of emerging market finance": "2",
  "journal of emerging technologies in accounting": "1",
  "journal of empirical finance": "3",
  "journal of employment counseling": "1",
  "journal of energy markets": "1",
  "journal of engineering and technology management - jet-m": "2",
  "journal of enterprise information management": "2",
  "journal of enterprising communities": "1",
  "journal of enterprising culture": "1",
  "journal of entrepreneurship": "1",
  "journal of entrepreneurship and public policy": "1",
  "journal of entrepreneurship in emerging economies": "1",
  "journal of environmental economics and management": "3",
  "journal of ethnic and migration studies": "2",
  "journal of european economic history": "1",
  "journal of european public policy": "3",
  "journal of european real estate research": "1",
  "journal of european social policy": "3",
  "journal of evolutionary economics": "2",
  "journal of experimental psychology: applied": "4",
  "journal of experimental psychology: general": "4",
  "journal of experimental psychology: learning memory and cognition": "3",
  "journal of experimental social psychology": "4",
  "journal of family and economic issues": "2",
  "journal of family business management": "1",
  "journal of family business strategy": "2",
  "journal of fashion marketing and management": "1",
  "journal of finance": "4*",
  "journal of financial and quantitative analysis": "4",
  "journal of financial econometrics": "3",
  "journal of financial economic policy": "1",
  "journal of financial economics": "4*",
  "journal of financial intermediation": "4",
  "journal of financial management of property and construction": "1",
  "journal of financial management, markets and institutions": "1",
  "journal of financial market infrastructures": "1",
  "journal of financial markets": "3",
  "journal of financial regulation and compliance": "1",
  "journal of financial reporting and accounting": "1",
  "journal of financial research": "3",
  "journal of financial services marketing": "1",
  "journal of financial services research": "3",
  "journal of financial stability": "3",
  "journal of fixed income": "2",
  "journal of foodservice business research": "1",
  "journal of forecasting": "2",
  "journal of forensic and investigative accounting (previously journal of forensic accounting)": "1",
  "journal of forest economics": "2",
  "journal of further and higher education": "1",
  "journal of futures markets": "3",
  "journal of gambling business and economics": "1",
  "journal of general management": "1",
  "journal of geographical systems": "1",
  "journal of global fashion marketing": "1",
  "journal of global information management": "2",
  "journal of global information technology management": "2",
  "journal of global marketing": "1",
  "journal of global mobility": "2",
  "journal of global optimization": "2",
  "journal of global responsibility": "1",
  "journal of globalization and development": "1",
  "journal of governmental & non-profit accounting": "1",
  "journal of happiness studies": "1",
  "journal of health economics": "3",
  "journal of health organization and management": "1",
  "journal of health services research and policy": "2",
  "journal of heuristics": "3",
  "journal of high technology management research": "2",
  "journal of higher education": "2",
  "journal of higher education policy and management": "1",
  "journal of historical research in marketing": "1",
  "journal of hospitality and tourism education": "1",
  "journal of hospitality and tourism management": "2",
  "journal of hospitality and tourism research": "2",
  "journal of hospitality and tourism technology": "1",
  "journal of hospitality marketing and management": "1",
  "journal of hospitality, leisure, sport and tourism education": "1",
  "journal of housing economics": "2",
  "journal of human capital": "3",
  "journal of human resources": "3",
  "journal of human resources in hospitality and tourism": "1",
  "journal of human values": "1",
  "journal of humanitarian logistics and supply chain management": "1",
  "journal of income distribution": "1",
  "journal of indian business research": "1",
  "journal of industrial and business economics": "1",
  "journal of industrial and management optimization": "1",
  "journal of industrial ecology": "2",
  "journal of industrial economics": "3",
  "journal of industrial relations": "2",
  "journal of industry, competition and trade": "2",
  "journal of information science": "2",
  "journal of information systems": "1",
  "journal of information systems education": "1",
  "journal of information technology": "4",
  "journal of information technology management": "1",
  "journal of information technology teaching cases": "1",
  "journal of informetrics": "1",
  "journal of innovation and knowledge": "1",
  "journal of innovation economics & management": "1",
  "journal of institutional and theoretical economics": "2",
  "journal of institutional economics": "3",
  "journal of intellectual capital": "2",
  "journal of intelligent manufacturing": "1",
  "journal of interactive advertising": "1",
  "journal of interactive marketing": "3",
  "journal of interdisciplinary economics": "1",
  "journal of international accounting research": "2",
  "journal of international accounting, auditing and taxation": "3",
  "journal of international business education": "2",
  "journal of international business studies": "4*",
  "journal of international development": "2",
  "journal of international economics": "4",
  "journal of international education in business": "1",
  "journal of international entrepreneurship": "1",
  "journal of international financial management and accounting": "2",
  "journal of international financial markets, institutions and money": "3",
  "journal of international management": "3",
  "journal of international marketing": "3",
  "journal of international money and finance": "3",
  "journal of international studies": "1",
  "journal of international trade and economic development": "1",
  "journal of internet commerce": "1",
  "journal of investment strategies": "1",
  "journal of islamic accounting and business research": "1",
  "journal of islamic business & management": "1",
  "journal of knowledge management": "2",
  "journal of labor economics": "4",
  "journal of labor research": "2",
  "journal of language and social psychology": "2",
  "journal of latin american studies": "2",
  "journal of law and economics": "3",
  "journal of law and society": "2",
  "journal of law, economics, and organization": "3",
  "journal of leadership studies": "1",
  "journal of legal studies": "3",
  "journal of macroeconomics": "2",
  "journal of macromarketing": "2",
  "journal of management": "4*",
  "journal of management accounting research": "2",
  "journal of management and governance": "1",
  "journal of management and organization": "2",
  "journal of management control": "2",
  "journal of management development": "1",
  "journal of management education": "2",
  "journal of management history": "1",
  "journal of management in engineering - asce": "2",
  "journal of management information systems": "4",
  "journal of management inquiry": "3",
  "journal of management sciences": "1",
  "journal of management studies": "4",
  "journal of management, spirituality and religion": "1",
  "journal of managerial psychology": "3",
  "journal of manufacturing systems": "1",
  "journal of manufacturing technology management": "1",
  "journal of marketing": "4*",
  "journal of marketing analytics": "1",
  "journal of marketing communications": "1",
  "journal of marketing education": "2",
  "journal of marketing for higher education": "1",
  "journal of marketing management": "2",
  "journal of marketing research": "4*",
  "journal of marketing theory and practice": "1",
  "journal of mathematical economics": "3",
  "journal of mathematical psychology": "3",
  "journal of mechanism and institution design": "1",
  "journal of media business studies": "1",
  "journal of media economics": "1",
  "journal of modelling in management": "1",
  "journal of modern african studies": "2",
  "journal of monetary economics": "4",
  "journal of money, credit and banking": "4",
  "journal of multi-criteria decision analysis": "1",
  "journal of multinational financial management": "2",
  "journal of multivariate analysis": "3",
  "journal of non-profit and public sector marketing": "1",
  "journal of nonparametric statistics": "2",
  "journal of nonverbal behavior": "2",
  "journal of occupational and environmental medicine": "2",
  "journal of occupational and organizational psychology": "4",
  "journal of occupational health psychology": "4",
  "journal of occupational rehabilitation": "2",
  "journal of operational risk": "2",
  "journal of operations management": "4*",
  "journal of optimization theory and applications": "3",
  "journal of organization design": "2",
  "journal of organizational and end user computing": "1",
  "journal of organizational behavior": "4",
  "journal of organizational behavior education": "1",
  "journal of organizational behavior management": "2",
  "journal of organizational change management": "2",
  "journal of organizational computing and electronic commerce": "1",
  "journal of organizational effectiveness": "2",
  "journal of organizational ethnography": "1",
  "journal of outdoor recreation and tourism": "1",
  "journal of pacific rim psychology": "1",
  "journal of pension economics and finance": "2",
  "journal of personal selling and sales management": "2",
  "journal of personality and social psychology": "4",
  "journal of personnel psychology": "2",
  "journal of place management and development": "2",
  "journal of policy analysis and management": "3",
  "journal of policy modeling": "2",
  "journal of policy research in tourism, leisure and events": "1",
  "journal of political economy": "4*",
  "journal of population economics": "3",
  "journal of portfolio management": "3",
  "journal of positive psychology": "1",
  "journal of post keynesian economics": "2",
  "journal of prediction markets": "1",
  "journal of product and brand management": "1",
  "journal of product innovation management": "4",
  "journal of productivity analysis": "2",
  "journal of professions and organization": "2",
  "journal of property investment and finance": "1",
  "journal of public administration research and theory": "4",
  "journal of public affairs": "1",
  "journal of public affairs education": "1",
  "journal of public budgeting, accounting and financial management": "2",
  "journal of public economic theory": "2",
  "journal of public economics": "3",
  "journal of public policy and marketing": "3",
  "journal of public procurement": "1",
  "journal of purchasing and supply management": "3",
  "journal of quality assurance in hospitality and tourism": "1",
  "journal of quality in maintenance engineering": "1",
  "journal of real estate finance and economics": "3",
  "journal of regional science": "3",
  "journal of regulatory economics": "2",
  "journal of rehabilitation": "1",
  "journal of relationship marketing": "1",
  "journal of research in interactive marketing": "1",
  "journal of retailing": "4",
  "journal of retailing and consumer services": "2",
  "journal of revenue and pricing management": "1",
  "journal of risk": "2",
  "journal of risk and insurance": "3",
  "journal of risk and uncertainty": "3",
  "journal of risk finance": "1",
  "journal of risk model validation": "1",
  "journal of risk research": "2",
  "journal of rural studies": "3",
  "journal of safety research": "2",
  "journal of scheduling": "1",
  "journal of school psychology": "3",
  "journal of science and technology policy management": "1",
  "journal of service management": "2",
  "journal of service research": "4",
  "journal of service theory and practice": "1",
  "journal of services marketing": "2",
  "journal of simulation": "2",
  "journal of small business and enterprise development": "2",
  "journal of small business and entrepreneurship": "1",
  "journal of small business management": "3",
  "journal of social entrepreneurship": "2",
  "journal of social marketing": "1",
  "journal of social policy": "3",
  "journal of social psychology": "1",
  "journal of sport and tourism": "1",
  "journal of sport management": "2",
  "journal of sports economics": "2",
  "journal of statistical planning and inference": "2",
  "journal of strategic contracting and negotiation": "1",
  "journal of strategic information systems": "4",
  "journal of strategic marketing": "2",
  "journal of strategy and management": "1",
  "journal of studies in international education": "1",
  "journal of supply chain management": "4",
  "journal of sustainable finance and investment": "1",
  "journal of sustainable tourism": "3",
  "journal of systems and information technology": "1",
  "journal of systems and software": "2",
  "journal of tax administration": "2",
  "journal of technology transfer": "3",
  "journal of the academy of marketing science": "4*",
  "journal of the american statistical association": "4",
  "journal of the american taxation association": "3",
  "journal of the asia pacific economy": "1",
  "journal of the association for information science and technology (jasist)": "3",
  "journal of the association for information systems": "4*",
  "journal of the association of environmental and resource economists": "3",
  "journal of the economic science association": "1",
  "journal of the economics of ageing": "2",
  "journal of the european economic association": "4",
  "journal of the history of economic thought": "2",
  "journal of the japanese and international economies": "2",
  "journal of the knowledge economy": "1",
  "journal of the operational research society": "3",
  "journal of the royal statistical society. series a: statistics in society": "3",
  "journal of the royal statistical society. series b: statistical methodology": "4",
  "journal of the royal statistical society. series c: applied statistics": "3",
  "journal of the textile institute": "1",
  "journal of theoretical and applied electronic commerce research": "1",
  "journal of time series analysis": "3",
  "journal of time series econometrics": "2",
  "journal of transnational management": "1",
  "journal of transport economics and policy": "1",
  "journal of transport geography": "2",
  "journal of transport history": "2",
  "journal of travel and tourism marketing": "2",
  "journal of travel research": "4",
  "journal of trust research": "1",
  "journal of urban economics": "3",
  "journal of vacation marketing": "1",
  "journal of vocational behavior": "4",
  "journal of vocational education and training": "1",
  "journal of work-applied management": "1",
  "journal of workplace learning": "1",
  "journal of world business": "4",
  "journal of world trade": "2",
  "judgment and decision making": "3",
  "knowledge and process management": "1",
  "knowledge management research and practice": "1",
  "kybernetes": "1",
  "kyklos": "2",
  "labor history": "2",
  "labor studies journal": "2",
  "labour": "1",
  "labour and industry: a journal of social and economic relations of work": "2",
  "labour economics": "3",
  "land economics": "3",
  "latin american business review": "1",
  "leadership": "2",
  "leadership and organization development journal": "1",
  "leadership in health services": "1",
  "leadership quarterly": "4",
  "learning organization": "1",
  "leisure sciences": "2",
  "leisure studies": "2",
  "letters in spatial and resource sciences": "1",
  "local economy": "2",
  "local government studies": "2",
  "long range planning": "4",
  "m@n@gement": "1",
  "macroeconomic dynamics": "2",
  "man and the economy": "1",
  "management": "1",
  "management accounting frontiers": "1",
  "management accounting research": "3",
  "management and labour studies": "1",
  "management and organization review": "3",
  "management and organizational history": "2",
  "management communication quarterly": "2",
  "management decision": "2",
  "management international review": "3",
  "management learning": "3",
  "management of environmental quality": "1",
  "management research": "1",
  "management research review": "1",
  "management review quarterly": "1",
  "management revue": "2",
  "management science": "4*",
  "managerial and decision economics": "2",
  "managerial auditing journal": "2",
  "managerial finance": "1",
  "managing leisure: an international journal": "1",
  "manchester school": "2",
  "manufacturing and service operations management": "3",
  "marine policy": "2",
  "marine resource economics": "1",
  "maritime economics and logistics": "1",
  "maritime policy and management": "2",
  "marketing education review": "1",
  "marketing intelligence and planning": "1",
  "marketing letters": "3",
  "marketing science": "4*",
  "marketing theory": "3",
  "mathematical finance": "3",
  "mathematical methods of operations research": "1",
  "mathematical programming": "4",
  "mathematical social sciences": "2",
  "mathematics of operations research": "3",
  "measuring business excellence": "1",
  "meditari accountancy research": "1",
  "metamorphosis- a journal of management research": "1",
  "metroeconomica": "1",
  "milbank quarterly": "3",
  "military psychology": "1",
  "mineral economics": "1",
  "mis quarterly executive": "2",
  "mis quarterly: management information systems": "4*",
  "mit sloan management review": "3",
  "multinational business review": "3",
  "multinational finance journal": "1",
  "museum management and curatorship": "2",
  "national institute economic review": "1",
  "national tax journal": "2",
  "natural resources journal": "1",
  "naval research logistics": "3",
  "negotiation journal": "2",
  "netnomics: economic research and electronic networking": "1",
  "network science": "1",
  "networks and spatial economics": "2",
  "new political economy": "3",
  "new technology, work and employment": "3",
  "new zealand economic papers": "1",
  "non-profit management & leadership": "1",
  "nonprofit and voluntary sector quarterly": "3",
  "nordic psychology": "1",
  "north american actuarial journal": "2",
  "north american journal of economics and finance": "2",
  "nutrition and food science": "1",
  "occupational and environmental medicine": "3",
  "occupational medicine": "1",
  "omega": "3",
  "online information review": "1",
  "online journal of applied knowledge management": "1",
  "open economies review": "2",
  "operational research": "1",
  "operations management education review": "1",
  "operations management research": "1",
  "operations research": "4*",
  "operations research letters": "2",
  "opsearch": "1",
  "optimization": "1",
  "or spectrum": "3",
  "organization": "3",
  "organization and environment": "3",
  "organization management journal": "1",
  "organization science": "4*",
  "organization studies": "4",
  "organizational behavior and human decision processes": "4",
  "organizational dynamics": "3",
  "organizational psychology review": "2",
  "organizational research methods": "4",
  "organizations and markets in emerging economies": "1",
  "oxford bulletin of economics and statistics": "3",
  "oxford development studies": "2",
  "oxford economic papers": "3",
  "oxford review of economic policy": "2",
  "pacific accounting review": "1",
  "pacific asia journal of the association for information systems": "2",
  "pacific basin finance journal": "2",
  "pacific economic review": "2",
  "pacific journal of optimization": "1",
  "papers in regional science": "3",
  "parliamentary affairs": "2",
  "pasos journal of tourism and cultural heritage": "1",
  "peace economics, peace science and public policy": "1",
  "personality and individual differences": "3",
  "personality and social psychology bulletin": "4",
  "personnel psychology": "4*",
  "personnel review": "2",
  "perspectives on public management & governance": "2",
  "pesquisa operacional": "1",
  "pharmacoeconomics": "2",
  "policing": "2",
  "policy and politics": "3",
  "policy and practice in health and safety": "1",
  "policy sciences": "1",
  "policy studies": "2",
  "political quarterly": "2",
  "political studies": "2",
  "politics and society": "3",
  "population studies": "1",
  "portuguese economic journal": "1",
  "post-communist economies": "1",
  "problems and perspectives in management": "1",
  "proceedings of the institution of mechanical engineers, part b: journal of engineering manufacture": "1",
  "production and operations management": "4",
  "production planning and control": "3",
  "progress in human geography": "3",
  "project management journal": "1",
  "prometheus": "2",
  "property management": "1",
  "psicothema": "1",
  "psihologija": "1",
  "psu research review: an international interdisciplinary journal": "1",
  "psychological bulletin": "4",
  "psychological reports": "1",
  "psychological research": "3",
  "psychological review": "4",
  "psychological science": "4*",
  "psychologie du travail et des organisations": "1",
  "psychologist": "1",
  "psychologist-manager journal": "1",
  "psychology and marketing": "3",
  "psychology of women quarterly": "3",
  "psychometrika": "3",
  "public administration": "4",
  "public administration and development": "2",
  "public administration quarterly": "1",
  "public administration review": "4*",
  "public choice": "3",
  "public integrity": "2",
  "public management review": "4",
  "public money and management": "2",
  "public opinion quarterly": "3",
  "public organization review": "2",
  "public performance & management review": "2",
  "public personnel management": "2",
  "public policy and administration": "2",
  "qualitative market research": "2",
  "qualitative research in accounting and management": "2",
  "qualitative research in financial markets": "1",
  "qualitative research in organizations and management": "1",
  "quality and reliability engineering international": "1",
  "quality assurance in education": "1",
  "quality progress": "1",
  "quantitative and qualitative analysis in social sciences": "1",
  "quantitative economics": "4",
  "quantitative finance": "3",
  "quantitative marketing and economics": "3",
  "quarterly journal of austrian economics": "1",
  "quarterly journal of economics": "4*",
  "quarterly journal of experimental psychology": "3",
  "quarterly journal of finance": "1",
  "quarterly journal of political science": "3",
  "quarterly review of economics and finance": "2",
  "queueing systems": "2",
  "r and d management": "3",
  "rae revista de administracao de empresas": "1",
  "rairo - operations research": "1",
  "rand journal of economics": "4",
  "rationality and society": "2",
  "rausp management journal": "1",
  "real estate economics": "3",
  "recherche et applications en marketing": "1",
  "regional and federal studies": "1",
  "regional science and urban economics": "3",
  "regional studies": "4",
  "regulation and governance": "3",
  "rehabilitation counseling bulletin": "1",
  "rehabilitation psychology": "2",
  "relations industrielles/industrial relations": "2",
  "reliability engineering and system safety": "3",
  "requirements engineering": "2",
  "research evaluation": "2",
  "research in economics": "1",
  "research in international business and finance": "2",
  "research in occupational stress and well being": "1",
  "research in organizational behavior": "3",
  "research in personnel and human resources management": "1",
  "research in the sociology of organizations": "3",
  "research in transportation economics": "1",
  "research on professional responsibility and ethics in accounting": "1",
  "research policy": "4*",
  "research technology management": "2",
  "resources policy": "2",
  "review of accounting and finance": "2",
  "review of accounting studies": "4",
  "review of african political economy": "2",
  "review of asset pricing studies": "3",
  "review of austrian economics": "1",
  "review of behavioral economics": "2",
  "review of behavioral finance": "1",
  "review of corporate finance studies": "3",
  "review of derivatives research": "2",
  "review of development economics": "2",
  "review of development finance": "2",
  "review of economic analysis": "1",
  "review of economic design": "2",
  "review of economic dynamics": "3",
  "review of economic studies": "4*",
  "review of economics and statistics": "4",
  "review of economics of the household": "2",
  "review of environmental economics and policy": "2",
  "review of european studies": "1",
  "review of finance": "4",
  "review of financial economics": "1",
  "review of financial studies": "4*",
  "review of income and wealth": "3",
  "review of industrial organization": "2",
  "review of international business and strategy": "1",
  "review of international economics": "2",
  "review of international political economy": "3",
  "review of law and economics": "2",
  "review of managerial science": "2",
  "review of marketing science": "1",
  "review of network economics": "2",
  "review of political economy": "2",
  "review of public personnel administration": "2",
  "review of quantitative finance and accounting": "3",
  "review of radical political economics": "1",
  "review of social economy": "2",
  "review of world economics": "2",
  "revista de contabilidad-spanish accounting review": "1",
  "revista de historia economica - journal of iberian and latin american economic history": "1",
  "revista espanola de financiacion y contabilidad": "1",
  "revue europeenne de psychologie appliquee": "1",
  "risk analysis": "4",
  "sa journal of human resource management": "1",
  "safety and reliability": "1",
  "scandinavian actuarial journal": "1",
  "scandinavian economic history review": "1",
  "scandinavian journal of economics": "3",
  "scandinavian journal of hospitality and tourism": "2",
  "scandinavian journal of information systems": "2",
  "scandinavian journal of management": "2",
  "scandinavian journal of psychology": "2",
  "scandinavian journal of statistics": "3",
  "scandinavian journal of work, environment and health": "3",
  "science and public policy": "2",
  "science and society": "2",
  "science and technology studies": "2",
  "science technology and human values": "2",
  "science, technology and society": "2",
  "scientometrics": "2",
  "scottish journal of political economy": "2",
  "series": "1",
  "service business": "1",
  "service industries journal": "2",
  "service science": "1",
  "services marketing quarterly": "1",
  "sex roles": "2",
  "siam journal on financial mathematics": "2",
  "siam journal on optimization": "3",
  "signs": "2",
  "simulation modelling practice and theory": "2",
  "small business economics": "3",
  "small enterprise research": "1",
  "small group research": "2",
  "social and environmental accountability journal": "1",
  "social choice and welfare": "3",
  "social enterprise journal": "1",
  "social forces": "3",
  "social justice research": "1",
  "social marketing quarterly": "1",
  "social networks": "2",
  "social policy and administration": "2",
  "social psychological and personality science": "3",
  "social responsibility journal": "1",
  "social science and medicine": "4",
  "social studies of science": "2",
  "social work in public health": "1",
  "society and business review": "2",
  "socio-economic planning sciences": "2",
  "socio-economic review": "4",
  "sociological methodology": "3",
  "sociological review": "3",
  "sociologie du travail": "2",
  "sociology": "4",
  "sociology of health and illness": "3",
  "south african journal of accounting research": "1",
  "south african journal of business management": "1",
  "south african journal of economics": "1",
  "south african journal of industrial psychology": "1",
  "south african journal of information management": "1",
  "south african journal of psychology": "1",
  "south asia economic journal": "1",
  "south asian journal of business and management cases": "1",
  "south asian journal of business studies": "1",
  "south asian journal of human resources management": "1",
  "southern economic journal": "2",
  "spanish journal of psychology": "1",
  "spatial economic analysis": "2",
  "sport management review": "2",
  "sport marketing quarterly": "1",
  "sport, business and management: an international journal": "1",
  "sport, exercise, and performance psychology": "1",
  "stata journal": "2",
  "statistical analysis and data mining": "1",
  "statistics and probability letters": "2",
  "strategic behavior and the environment": "1",
  "strategic change": "2",
  "strategic entrepreneurship journal": "4",
  "strategic management journal": "4*",
  "strategic organization": "3",
  "strategy and leadership": "1",
  "stress and health": "3",
  "structural change and economic dynamics": "2",
  "studies in agricultural economics": "1",
  "studies in economics and finance": "1",
  "studies in higher education": "3",
  "studies in indian politics": "1",
  "studies in nonlinear dynamics and econometrics": "2",
  "supply chain forum": "1",
  "supply chain management": "3",
  "sustainability accounting, management and policy journal": "2",
  "swiss journal of economics and statistics": "1",
  "symbolic interaction": "2",
  "symphonya. emerging issues in management": "1",
  "system dynamics review": "2",
  "systemic practice and action research": "2",
  "systems research and behavioral science": "2",
  "tamara: journal for critical organization inquiry": "1",
  "teaching in higher education": "2",
  "teaching public administration": "1",
  "team performance management": "1",
  "technological forecasting and social change": "3",
  "technology analysis and strategic management": "2",
  "technology innovation management review": "1",
  "technovation": "3",
  "telecommunications policy": "1",
  "tertiary education and management": "1",
  "the data base for advances in information systems": "2",
  "the forum for social economics": "1",
  "the international journal of aerospace psychology": "1",
  "the journal of applied behavioral science": "2",
  "theoretical economics": "4",
  "theory and decision": "2",
  "theory, culture and society": "3",
  "third world quarterly": "2",
  "thunderbird international business review": "2",
  "tijdschrift voor economische en sociale geografie": "1",
  "time and society": "2",
  "top": "1",
  "total quality management and business excellence": "2",
  "tourism analysis": "2",
  "tourism economics": "2",
  "tourism geographies": "2",
  "tourism management": "4",
  "tourism management perspectives": "2",
  "tourism planning and development": "2",
  "tourism recreation research": "2",
  "tourism review": "1",
  "tourism, culture and communication": "1",
  "tourist studies": "1",
  "town planning review": "2",
  "tpm - testing, psychometrics, methodology in applied psychology": "1",
  "tqm journal": "1",
  "transactions of the institute of british geographers": "1",
  "transfer": "2",
  "transforming government: people, process and policy": "2",
  "transnational corporations review": "1",
  "transport policy": "2",
  "transport reviews": "2",
  "transportation": "2",
  "transportation research, part a: policy and practice": "3",
  "transportation research, part d: transport and environment": "3",
  "transportation research, part e: logistics and transportation review": "3",
  "transportation research, series b: methodological": "4",
  "transportation science": "3",
  "urban studies": "3",
  "utilities policy": "1",
  "valuation studies": "1",
  "venture capital": "2",
  "vikalpa": "1",
  "vision": "1",
  "visitor studies": "1",
  "voluntas": "2",
  "west european politics": "3",
  "work": "1",
  "work and occupations": "3",
  "work and stress": "4",
  "work organisation, labour and globalisation": "1",
  "work, aging and retirement": "2",
  "work, employment and society": "4",
  "world bank economic review": "3",
  "world bank research observer": "2",
  "world development": "3",
  "world economy": "2",
  "world leisure journal": "1",
  "world review of entrepreneurship, management and sustainable development": "1",
  "world review of intermodal transportation research": "1",
  "world tax journal": "1",
  "worldwide hospitality and tourism themes": "1",
  "young consumers": "1",
  "zeitschrift fur arbeits- und organisationspsychologie": "1",
  "zeitschrift fur psychologie / journal of psychology": "2",
};

// Impact Factors (OpenAlex 2yr mean citedness) - IF > 5
// Covers all disciplines: science, engineering, medicine, social science, etc.
export const JOURNAL_IF: Record<string, number> = {
  "academy of management journal": 10.5,
  "academy of management review": 12.3,
  "accounts of chemical research": 15.9,
  "acs catalysis": 11.8,
  "acs energy letters": 13.6,
  "acs nano": 13.6,
  "acs sensors": 8.8,
  "acta biomaterialia": 7.4,
  "acta materialia": 8.4,
  "acta neuropathologica": 9.6,
  "acta physico-chimica sinica": 9.6,
  "administrative science quarterly": 9.2,
  "advanced drug delivery reviews": 12.1,
  "advanced energy materials": 16.1,
  "advanced functional materials": 12.9,
  "advanced materials": 18.9,
  "advanced science": 7.5,
  "african journal of agricultural research": 21.9,
  "african journal of microbiology research": 14.4,
  "american economic review": 12.8,
  "angewandte chemie international edition": 12.8,
  "applied catalysis b: environmental": 14.2,
  "applied energy": 12.5,
  "applied mechanics and materials": 8.8,
  "automation in construction": 10.0,
  "biomaterials": 9.6,
  "biomedicine & pharmacotherapy": 7.3,
  "biosensors and bioelectronics": 9.2,
  "biotechnology advances": 9.6,
  "bulletin of the american mathematical society": 9.0,
  "business horizons": 8.9,
  "business strategy and the environment": 13.4,
  "cancer letters": 8.5,
  "carbohydrate polymers": 10.0,
  "carbon": 9.9,
  "catalysis communications": 10.9,
  "cell": 34.3,
  "cell death and differentiation": 8.4,
  "cell death and disease": 7.7,
  "cement and concrete composites": 11.9,
  "cement and concrete research": 10.3,
  "chemical engineering journal": 9.4,
  "chemical reviews": 44.5,
  "chemical society reviews": 34.4,
  "chemosphere": 8.4,
  "chinese journal of catalysis (chinese version)": 12.8,
  "composites part b engineering": 11.1,
  "composites science and technology": 9.8,
  "computer methods in applied mechanics and engineering": 7.3,
  "computers & education": 10.3,
  "computers & security": 7.2,
  "computers and electronics in agriculture": 8.6,
  "computers in human behavior": 9.3,
  "construction and building materials": 8.0,
  "coordination chemistry reviews": 17.3,
  "corrosion science": 9.1,
  "current opinion in structural biology": 7.5,
  "desalination": 8.9,
  "developmental cell": 8.8,
  "diabetes care": 10.6,
  "drugs": 9.7,
  "earth-science reviews": 8.6,
  "ebiomedicine": 8.2,
  "ecological indicators": 7.8,
  "education and information technologies": 8.9,
  "energy": 8.6,
  "energy & environmental science": 24.9,
  "energy conversion and management": 10.3,
  "energy economics": 10.6,
  "energy reports": 8.1,
  "energy storage materials": 12.3,
  "engineering geology": 7.5,
  "entrepreneurship theory and practice": 10.5,
  "environment international": 8.8,
  "environmental science & technology": 8.9,
  "european respiratory journal": 7.3,
  "eurosurveillance": 7.2,
  "finance research letters": 7.4,
  "food chemistry": 8.0,
  "food hydrocolloids": 10.7,
  "genome biology": 8.1,
  "global change biology": 8.3,
  "gut": 8.9,
  "ieee journal on selected areas in communications": 8.4,
  "ieee transactions on fuzzy systems": 8.1,
  "ieee transactions on image processing": 7.5,
  "ieee transactions on knowledge and data engineering": 7.7,
  "ieee transactions on medical imaging": 7.4,
  "ieee transactions on pattern analysis and machine intelligence": 11.2,
  "ieee/acm transactions on networking": 7.5,
  "immunity": 19.4,
  "immunological reviews": 8.1,
  "information systems research": 5.0,
  "international journal of hydrogen energy": 8.4,
  "international journal of innovative science and research technology (ijisrt)": 12.8,
  "international journal of mechanical sciences": 9.0,
  "international journal of molecular medicine": 8.9,
  "international journal of nanomedicine": 7.9,
  "international journal of oncology": 12.9,
  "international journal of production economics": 8.0,
  "jama": 7.5,
  "jama network open": 7.6,
  "journal for immunotherapy of cancer": 7.5,
  "journal of accounting and economics": 5.5,
  "journal of accounting research": 5.2,
  "journal of applied psychology": 6.6,
  "journal of business ethics": 6.6,
  "journal of business research": 10.5,
  "journal of business venturing": 10.0,
  "journal of cleaner production": 11.0,
  "journal of clinical investigation": 8.2,
  "journal of colloid and interface science": 9.2,
  "journal of consumer research": 7.2,
  "journal of controlled release": 8.6,
  "journal of cosmology and astroparticle physics": 7.3,
  "journal of energy chemistry": 13.8,
  "journal of energy storage": 8.8,
  "journal of environmental management": 7.7,
  "journal of finance": 8.0,
  "journal of financial economics": 8.2,
  "journal of hazardous materials": 8.6,
  "journal of international business studies": 8.6,
  "journal of management": 9.3,
  "journal of management studies": 8.6,
  "journal of manufacturing processes": 7.3,
  "journal of marketing": 12.9,
  "journal of marketing research": 6.1,
  "journal of material science and technology": 15.5,
  "journal of materials chemistry": 26.0,
  "journal of membrane science": 7.4,
  "journal of operations management": 7.8,
  "journal of the academy of marketing science": 11.4,
  "journal of the american chemical society": 13.9,
  "journal of the american medical informatics association": 9.5,
  "journal of the chemical society (resumed)": 9.5,
  "journal of the chemical society dalton transactions": 56.3,
  "journal of the chemical society faraday transactions 1 physical chemistry in condensed phases": 66.0,
  "journal of the chemical society perkin transactions 1": 28.0,
  "journal of the chemical society transactions": 30.0,
  "kidney international": 11.8,
  "landscape and urban planning": 8.5,
  "management science": 5.4,
  "marketing science": 5.0,
  "materials today": 10.8,
  "mechanical systems and signal processing": 7.7,
  "metabolism": 7.4,
  "mis quarterly": 7.3,
  "molecular cell": 11.7,
  "molecular psychiatry": 7.4,
  "nano energy": 16.0,
  "nano letters": 7.5,
  "nature": 16.0,
  "nature biotechnology": 11.2,
  "nature cell biology": 14.3,
  "nature chemical biology": 8.6,
  "nature chemistry": 16.2,
  "nature climate change": 11.2,
  "nature communications": 14.7,
  "nature genetics": 15.2,
  "nature immunology": 11.3,
  "nature materials": 19.5,
  "nature medicine": 25.8,
  "nature methods": 18.2,
  "nature nanotechnology": 23.7,
  "nature neuroscience": 15.7,
  "nature photonics": 22.0,
  "nature physics": 10.2,
  "nature reviews drug discovery": 12.1,
  "nature reviews genetics": 14.8,
  "nature reviews. neuroscience": 12.7,
  "nature structural & molecular biology": 9.3,
  "neuron": 11.6,
  "new england journal of medicine": 25.9,
  "nucleic acids research": 13.3,
  "operations research": 3.2,
  "organization science": 5.0,
  "pharmacological research": 9.3,
  "philosophical transactions of the royal society b biological sciences": 9.0,
  "physical review letters": 7.5,
  "physics reports": 14.3,
  "phytomedicine": 7.2,
  "phytopathology": 7.5,
  "proceedings of the ieee": 8.4,
  "proceedings of the national academy of sciences": 7.2,
  "psychological bulletin": 8.4,
  "rare metals": 9.7,
  "reliability engineering & system safety": 9.1,
  "remote sensing of environment": 9.0,
  "renewable and sustainable energy reviews": 14.0,
  "renewable energy": 7.9,
  "research policy": 9.5,
  "resources conservation and recycling": 8.5,
  "resources policy": 9.1,
  "review of financial studies": 6.8,
  "science": 17.3,
  "science advances": 10.7,
  "science bulletin": 7.5,
  "science translational medicine": 13.2,
  "separation and purification technology": 8.1,
  "small": 7.6,
  "soil biology and biochemistry": 10.6,
  "space science reviews": 7.4,
  "strategic management journal": 7.8,
  "sustainable cities and society": 11.3,
  "technological forecasting and social change": 12.9,
  "the astrophysical journal letters": 7.7,
  "the journal of experimental medicine": 8.6,
  "the journal of finance": 10.6,
  "the journal of negro education": 16.0,
  "the lancet": 17.0,
  "the lancet infectious diseases": 10.1,
  "the lancet neurology": 13.2,
  "the lancet oncology": 9.6,
  "the plant cell": 9.3,
  "the quarterly journal of economics": 15.8,
  "the science of the total environment": 9.4,
  "theranostics": 10.1,
  "tourism management": 8.4,
  "trac trends in analytical chemistry": 11.5,
  "transactions of the faraday society": 21.0,
  "trends in cell biology": 7.7,
  "trends in food science & technology": 12.0,
  "trends in pharmacological sciences": 8.4,
  "työväentutkimus vuosikirja": 22.5,
  "ultrasonics sonochemistry": 8.1,
  "water research": 10.6,
};

// ABS: 1635 journals
// IF: 226 journals
